FROM ubuntu

COPY node-v14.17.6-linux-x64 /opt/node-v14.17.6-linux-x64/
RUN cd /opt
ENV PATH /opt/node-v14.17.6-linux-x64/bin:$PATH
RUN mkdir express
COPY node_modules /opt/express/node_modules/
COPY ./server.js /opt/express/
COPY ./ximalaya_router.js /opt/express/
COPY ./classify_router.js /opt/express/
RUN cd /opt/express 
EXPOSE 8000
ENTRYPOINT node /opt/express/server.js